config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get '/signup', to: 'users#new'

  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    resources :incomes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  has_many :income_values, dependent: :destroy

  validates :income_name, presence: true, length: { in: 2..20 }
  validate :income_name_is_invalid_for_nil


  # 収入科目が空白の登録は無効
  def income_name_is_invalid_for_nil
    errors.add(:income_name, "は２文字以上20文字以内が必要です。") if income_name.blank?
  end
end

app/models/income_value.rb
class IncomeValue < ApplicationRecord
  belongs_to :income
end

app/models/user.rb
class User < ApplicationRecord
  has_many :incomes, dependent: :destroy
  # 「remember_token」という仮想の属性を作成する
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 30 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, length: { in: 6..20 }, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返す
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了する
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  # paramsハッシュからユーザー（:id）を取得する
  def set_user
    @user = User.find(params[:id])
  end

  # paramsハッシュからユーザー（:user_id）を取得する
  def set_user_id
    @user = User.find(params[:user_id])
  end

  # ログイン済みのユーザーか確認する
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end

  # アクセスしたユーザーが現在ログインしているユーザーか確認する
  def correct_user
    @user = User.find(params[:id])
    redirect_to login_url unless current_user?(@user)
  end

    # アクセスしたユーザーが現在ログインしているユーザー（:user_id）か確認する
    def correct_user_id
      @user = User.find(params[:user_id])
      redirect_to login_url unless current_user?(@user)
    end

  # システム管理権限者かどうか判定する
  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_user_id, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :correct_user_id, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_income, only: [:edit, :destroy]
  
  def index
    @incomes = @user.incomes
  end
  
  def new
    @income = @user.incomes.build
  end

  def create
    @income = @user.incomes.build
    income_params.each do |item|
      if @income.update_attributes(item)
        flash[:success] = "収入科目を登録しました。"
        redirect_to user_incomes_url(@user)
      else
        flash.now[:danger] = "登録に失敗しました。やり直してください。"
        render :new
      end
    end
  end
  
  def edit
  end

  def update
    income_params.each do |id, item|
      @income = @user.incomes.find(id)
      if @income.update_attributes(item)
        flash[:success] = "収入科目を更新しました。"
        redirect_to user_incomes_url(@user)
      else
        flash.now[:danger] = "更新に失敗しました。やり直してください。"
        render :edit
      end
    end
  end

  def destroy
    @income.destroy
    flash[:success] = "#{@income.income_name}を削除しました。"
    redirect_to user_incomes_url(current_user)
  end

  private
    def income_params
      params.require(:user).permit(incomes: :income_name)[:incomes]
    end

    def set_income
      @income = @user.incomes.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user # 引数として指定するための()を省略 log_in(user) / redirect_to(user)
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = "認証に失敗しました。やり直してください。"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user # ユーザー登録成功後、ログインする
      flash[:success] = "新規登録に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      flash.now[:danger] = "更新に失敗しました。やり直してください。"
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
                                    :birthday, :sex, :prefecture, :occupation, :marriage,
                                    :annual_income)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title( page_name = "" )
    base_title = "Asset Management"
    if page_name.empty?
      base_title
    else
      page_name + "|" + base_title
    end
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 引数に渡されたユーザーオブジェクトでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # 永続セッションを記憶する（Userモデルを参照）
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end


  # 一時的セッションにいるユーザーを返す
  # それ以外の場合はcookiesに対応するユーザーを返す
  def current_user
    # findメソッド：session[:user_id]が存在しない場合、例外（エラーが発生）が発生
    # find_byメソッド：session[:user_id]が存在しない場合、nil（「何も無い」）が返される
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # 渡されたユーザーがログイン済みのユーザーであればtrueを返す
  def current_user?(user)
    user == current_user
  end

  # 現在ログイン中のユーザーがいればtrue、そうでなければfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # セッションと@current_userを破棄する
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶しているURL（またはデフォルトURL）にリダイレクトする
  def redirect_back_or(default_url)
    redirect_to(session[:forwarding_url] || default_url)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを記憶する
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages' %>
  
  <%= f.fields_for "incomes[]", @income do |i| %>
    <%= i.label :income_name, class: "label-#{yield(:class_text)}" %>
    <%= i.text_field :income_name, class: "form-control" %>
  <% end %>

  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/incomes/edit.html.erb
<% provide(:title, "収入科目編集") %>
<% provide(:class_text, 'income--edit' ) %>
<% provide(:btn_text, "更新") %>
<h2>収入科目編集</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3" %>
    <%= form_with(model: @user, url: user_income_path(current_user, @income), method: :patch, local: true) do |f| %>
      <%= f.fields_for 'incomes[]', @income do |i| %>
        <%= i.label :income_name, class: "label-#{yield(:class_text)}" %>
        <%= i.text_field :income_name, class: "form-control" %>
      <% end %>

      <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/incomes/index.html.erb
<% provide(:title, "収入科目一覧") %>
<h2>収入科目一覧</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-borderless income-table">
      <thead>
        <tr>
          <th>収入科目</th>
          <th></th>
          <th></th>
        <tr>
      </thead>
      <tbody>
        <% @incomes.each do |income| %>
          <tr>
            <td><%= income.income_name %></td>
            <td><%= link_to "編集", edit_user_income_path(@user, income), class: "btn btn-success btn-sm" %></td>
            <td>
              <%= link_to "削除", user_income_path(@user, income), method: :delete,
                  data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= link_to "収入科目を追加する", new_user_income_path(@user), class: "btn btn-primary income-button" %>
    </div>
  </div>
</div>

app/views/incomes/new.html.erb
<% provide(:title, "収入科目登録") %>
<% provide(:class_text, 'income--new' ) %>
<% provide(:btn_text, "登録") %>
<h2>収入科目新規登録</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3" %>
    <%= form_with(model: @user, url: user_incomes_path(current_user), method: :post, local: true) do |f| %>
      <%= f.fields_for 'incomes[]', @income do |i| %>
        <%= i.label :income_name, class: "label-#{yield(:class_text)}" %>
        <%= i.text_field :income_name, class: "form-control" %>
      <% end %>

      <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand navbar-fixed-top">
    <div class="container">
      <%= link_to "資産管理共有アプリ", '#', id: "logo" %>
        <ul class="nav navbar-nav navbar-right">
          
          <!-- 勤怠6章6.4を参考にする -->
          <% if logged_in? %>
            <!-- ↓↓↓ <%= link_to "Top", root_path %> とルートパスを明示した記述にする -->
            <li><%= link_to "トップ", '#', class: "nav-item" %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-item" data-toggle="dropdown">
                収支科目 <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "収入科目一覧", user_incomes_path(current_user) , class: "nav-item" %></li>
                <li><%= link_to "支出科目一覧", '#' , class: "nav-item" %></li>
              </ul>
            </li>
            <li><%= link_to "ユーザー一覧", users_path, class: "nav-item" %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-item" data-toggle="dropdown">
                アカウント <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "ユーザ情報", current_user, class: "nav-item" %></li> <!-- user_path(current_user) と同じ -->
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-item" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "ログイン", login_path, class: "nav-item" %></li>
          <% end %>
        </ul>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="aler alert-danger">
      入力エラーが<%= @user.errors.count %>件ありました。
    </div>
  
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages' %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :password_confirmation, class: "form-control" %>

  <%= f.label :birthday, class: "label-#{yield(:class_text)}" %>
  <%= f.date_field :birthday, class: "form-control" %>

  <%= f.label :sex, class: "label-#{yield(:class_text)}" %><br>
  <%= f.radio_button :sex, "男性", class: "radio-button" %>&nbsp;男性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button :sex, "女性", class: "radio-button" %>&nbsp;女性<br>

  <%= f.label :prefecture, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :prefecture, class: "form-control" %>

  <%= f.label :occupation, class: "label-#{yield(:class_text)}" %><br>
  <%= f.select :occupation, [ ["経営者・会社役員", "経営者・会社役員"], ["会社員（正社員）", "会社員（正社員）"], ["会社員（契約社員）", "会社員（契約社員）"],
                              ["会社員（派遣社員）", "会社員（派遣社員）"], ["パート・アルバイト", "パート・アルバイト"], ["公務員", "公務員"],
                              ["自営業・フリーランス", "自営業・フリーランス"], ["専業主婦・主夫", "専業主婦・主夫"], ["大学生・大学院生", "大学生・大学院生"],
                              ["専門学校生・短大生", "専門学校生・短大生"], ["士業（弁護士・公認会計士・税理士等", "士業（弁護士・公認会計士・税理士等"], ["無職", "無職"],
                              ["定年退職", "定年退職"], ["その他", "その他"] ], { prompt: "選択してください" }, { class: 'form-control' } %><br>
  
  <%= f.label :marriage, class: "label-#{yield(:class_text)}" %><br>
  <%= f.radio_button :marriage, "未婚" %>&nbsp;未婚&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.radio_button :marriage, "既婚" %>&nbsp;既婚<br>
  
  <!-- 子供の有無 -->
  
  <%= f.label :annual_income, class: "label-#{yield(:class_text)}" %><br>
  <%= f.select :annual_income, [ ["200万円未満", "200万円未満"], ["200万円以上 〜 400万円未満", "200万円以上 〜 400万円未満"],
                                ["400万円以上 〜 600万円未満", "400万円以上 〜 600万円未満"], ["600万円以上 〜 800万円未満", "600万円以上 〜 800万円未満"],
                                ["800万円以上 〜 1,000万円未満", "800万円以上 〜 1,000万円未満"], ["1,000万円以上 〜 2,000万円未満", "1,000万円以上 〜 2,000万円未満"],
                                ["2,000万円以上", "2,000万円以上"] ], { prompt: "選択してください" }, { class: 'form-control' } %><br>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報編集") %>
<% provide(:class_text, "user--edit") %>
<% provide(:button_text, "更新") %>

<h2>ユーザー情報の編集</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "ユーザー一覧") %>
<h2>ユーザー一覧</h2>

<div class="col-md-12">
  <%= will_paginate %>
  <table class="table table-hover" id="table-users">
    <thead>
      <tr>
        <th>名前</th>
        <th>生年月日</th>
        <th>性別</th>
        <th>住まい</th>
        <th>職業</th>
        <th>未婚/既婚</th>
        <th>年収</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% unless user.admin? %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.birthday %></td>
            <td><%= user.sex %></td>
            <td><%= user.prefecture %></td>
            <td><%= user.occupation %></td>
            <td><%= user.marriage %></td>
            <td><%= user.annual_income %></td>
            <td>
              <% if current_user.admin? && !current_user?(user) %>
                <%= link_to "削除", user, method: :delete,
                    data: { confirm: "#{user.name}のデータを削除してよろしいですか？" },
                    class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      <%end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<% provide(:class_text, "signup") %>
<% provide(:button_text, "新規登録") %>

<h2>ユーザー登録</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, "@user.name") %>

<div class="col-md-8 col-md-offset-2">
  <h2>ユーザー情報</h2>

  <table class="table table-borderless user-table">
    <tr>
      <td>名前：</td>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <td>メールアドレス：</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td>生年月日：</td>
      <td><%= @user.birthday %></td>
    </tr>
    <tr>
      <td>性別：</td>
      <td><%= @user.sex %></td>
    </tr>
    <tr>
      <td>住まい：</td>
      <td><%= @user.prefecture %></td>
    </tr>
    <tr>
      <td>職業：</td>
      <td><%= @user.occupation %></td>
    </tr>
    <tr>
      <td>婚姻：</td>
      <td><%= @user.marriage %></td>
    </tr>
    <tr>
      <td>子供：</td>
      <td><%= @user.children %></td>
    </tr>
    <tr>
      <td>年収：</td>
      <td><%= @user.annual_income %></td>
    </tr>
  </table>

  <%= link_to "編集", edit_user_path(@user), class: "btn btn-primary btn-block" %>
</div>